local kit = require "zomboid:buildings/_kit"

return kit.building {
    kind = "fire_station",
    title = "пожарная часть",
    color = {255, 90, 70},
    zones = {"downtown", "suburb"},
    weight = 2,
    cells = 1,
    car_color = "red",
    materials = {
        wall = {"base:brick", "zomboid:siding_red"},
        inner = "zomboid:bld_plaster",
        floor = "zomboid:bld_concrete",
        floor2 = "zomboid:tiles",
        stair = "zomboid:bld_concrete",
        slab = "zomboid:bld_step",
    },
    floors = {
        {
            "#GGG##GGG##WWDWW#WWW#",
            "#.........#d..d...uu#",
            "#.L....L..#.........W",
            "#.........#d.d.L....#",
            "#.v.......#.........W",
            "#.........#kkk......#",
            "#.........#%%%D%%%%%#",
            "#.L....L..D......%44#",
            "#.........#llll..%45#",
            "#.........#......%36#",
            "#cc.....cc#cc.L..%27#",
            "#lllll.lll#......%18#",
            "#.........#llll.....#",
            "#WW#W#D#WW#WW#WD#WWW#",
        },
        {
            "#WW#W#W#WW#WW#WW#WWW#",
            "#b.b.b.b.b#uu...t...#",
            "#.........#.........W",
            "#...L...L.#u...L....#",
            "#b.b.b.b.b#.........W",
            "#.........#kkon.kf..#",
            "#lllll.lll#......%%%#",
            "#.........D.dd...%00#",
            "#.........#.dd...%00#",
            "#%%%%D%%%%#......%00#",
            "#:n:n::m::#..L...%00#",
            "#::;::::::#......%00#",
            "#:::::::::#ccc......#",
            "#WW#WW#WW##WW#WW#WWW#",
        },
    },
    loot = {
        locker = {
            {"zomboid:axe", 4, 1, 1}, {"zomboid:crowbar", 3, 1, 1}, {"zomboid:flashlight", 4, 1, 1},
            {"zomboid:boots", 3, 1, 1}, {"zomboid:raincoat", 3, 1, 1}, {"zomboid:bandage", 2, 1, 2},
            {"zomboid:leather_jacket", 1, 1, 1}, {"zomboid:hammer", 1, 1, 1},
        },
        crate = {
            rolls = {1, 3},
            {"zomboid:gas_can", 3, 1, 1}, {"zomboid:gas_can_empty", 3, 1, 1}, {"zomboid:rag", 3, 2, 4},
            {"zomboid:water_bottle", 3, 1, 3}, {"zomboid:bandage", 2, 1, 3}, {"zomboid:axe", 1, 1, 1},
            {"zomboid:disinfectant", 1, 1, 1},
        },
        kitchen_cabinet = {
            {"zomboid:canned_beans", 5, 1, 3}, {"zomboid:cooking_pot", 2, 1, 1}, {"zomboid:frying_pan", 2, 1, 1},
            {"zomboid:matches", 2, 1, 2}, {"zomboid:map", 2, 1, 1}, {"zomboid:radio", 2, 1, 1},
        },
    },
    zombies = {count = {3, 6}, shirts = {"firefighter", "firefighter", "firefighter", "gray"}},
}
