local kit = require "zomboid:buildings/_kit"

return kit.building {
    kind = "military",
    title = "блокпост",
    color = {95, 115, 60},
    zones = {"outskirts", "highway"},
    weight = 2,
    cells = 1,
    car_color = "green",
    door = 11,
    materials = {
        wall = {"zomboid:bld_concrete", "zomboid:bld_corrugated"},
        inner = "zomboid:bld_concrete",
        floor = "zomboid:bld_concrete",
    },
    legend = {
        A = {"zomboid:bld_ammo_crate", g = "base:dirt", out = true, face = true},
    },
    floors = {{
        "||||||||||___||||||||||",
        "|,,,,,,xx,___,xx,,,,,,|",
        "|,PRRP,x,,___,,x,,,,,,|",
        "|,ROHR,,,,___,,,yyyyy,|",
        "|,ROOR,,,,___,,,y,,,y,|",
        "|,PRRP,,,,___,,,y,V,y,|",
        "|,,,,,,,,,___,,,y,,,y,|",
        "|,,,,,,,,,___,,,,,,,,,|",
        "|,,,,,,,,,,,,,,,,,,,,,|",
        "|#W#WD#W#W#,,##W#D#W##|",
        "|#b.b.b.b.#,,#dd....a#|",
        "|W...L....W,,W..L...aW|",
        "|#b.b.b.b.#,,#c.....c#|",
        "|#........#,,#########|",
        "|#l.l.l.ll#,,,,,,,,,,,|",
        "|##########,,,##D#####|",
        "|,yyyyy,,,,,,,#a....a#|",
        "|,y,A,y,,,,,,,#a.L..l#|",
        "|,y,,,y,,,,,,,#aa..ll#|",
        "|,,,,,,,,,,,,,########|",
        "|,,xx,,,,,,,,,,,,,,xx,|",
        "|,,,,,,,,,,,,,,,,,,,,,|",
        "|||||||||||||||||||||||",
    }},
    loot = {
        ammo_crate = {
            rolls = {1, 3},
            {"zomboid:ammo_9mm", 4, 6, 15}, {"zomboid:shotgun_shells", 3, 4, 10}, {"zomboid:pistol", 1, 1, 1},
            {"zomboid:shotgun", 0.6, 1, 1}, {"zomboid:canned_beans", 2, 2, 4}, {"zomboid:water_bottle", 2, 2, 3},
            {"zomboid:bandage", 2, 2, 4}, {"zomboid:antibiotics", 0.5, 1, 1}, {"zomboid:siren.item", 0.3, 1, 1},
        },
        locker = {
            {"zomboid:boots", 3, 1, 1}, {"zomboid:leather_jacket", 2, 1, 1}, {"zomboid:hiking_bag", 2, 1, 1},
            {"zomboid:flashlight", 3, 1, 1}, {"zomboid:knife", 3, 1, 1}, {"zomboid:ammo_9mm", 2, 3, 8},
            {"zomboid:bandage", 2, 1, 3}, {"zomboid:map", 2, 1, 1}, {"zomboid:radio", 2, 1, 1},
            {"zomboid:cigarettes", 1, 1, 2},
        },
        crate = {
            {"zomboid:canned_beans", 5, 2, 5}, {"zomboid:water_bottle", 4, 2, 4}, {"zomboid:matches", 2, 1, 2},
            {"zomboid:rag", 2, 2, 4}, {"zomboid:gas_can", 1, 1, 1}, {"zomboid:crowbar", 1, 1, 1},
        },
    },
    zombies = {count = {3, 5}, yard = {4, 7}, shirts = {"military"}},
}
