local kit = require "zomboid:buildings/_kit"

return kit.building {
    kind = "supermarket",
    title = "супермаркет",
    color = {240, 220, 140},
    zones = {"downtown", "suburb"},
    weight = {downtown = 1, suburb = 1},
    cells = 2,
    materials = {
        wall = {"base:brick", "zomboid:bld_plaster", "zomboid:bld_concrete"},
        inner = "zomboid:bld_plaster",
        floor = "zomboid:tiles",
        floor2 = "zomboid:bld_linoleum",
    },
    floors = {{
        "=======================================",
        "=======================================",
        "=====V=================================",
        "=======================================",
        "=======================================",
        "=======================================",
        "_______________________________________",
        "_______________________________________",
        "#WWWWWWWWWWDWWWWWWWWWWWWWWWDWWWWWWWWWW#",
        "W.....................................W",
        "#.....L.......L.......L.......L.......#",
        "#...kk...kk...kk......kk...kk...kk....#",
        "W.....................................W",
        "#c...................................f#",
        "#c..ssssssssssss....sssssssssssss....f#",
        "Wc..ssssssssssss....sssssssssssss....fW",
        "#c...................................f#",
        "#c...................................f#",
        "Wc..ssssssssssss....sssssssssssss....fW",
        "#c..ssssssssssss....sssssssssssss....f#",
        "#c....L.......L.......L.......L......f#",
        "Wc...................................fW",
        "#c..ssssssssssss....sssssssssssss....f#",
        "#c..ssssssssssss....sssssssssssss....f#",
        "Wc...................................fW",
        "#%%%%%%%D%%%%%%%%%%%%%%%%%%%%%D%%%%%%%#",
        "#sssss.sssss....%.....%ccccccccc......#",
        "#.....L.........%..L..D......L........#",
        "#sssss.sssss....%d.d..%cccccccc.......#",
        "#cccc...........%u...w%.......cc.cc.c.#",
        "#WW#WD#WW#WW#WW#WW#WW#WW#WW#WW#WWDWW#W#",
    }},
    loot = {
        shelf = {
            rolls = {2, 6},
            {"zomboid:canned_beans", 6, 1, 3}, {"zomboid:chips", 5, 1, 3}, {"zomboid:chocolate", 3, 1, 2},
            {"zomboid:soda", 4, 1, 3}, {"zomboid:water_bottle", 4, 1, 3}, {"zomboid:bread", 3, 1, 2},
            {"zomboid:cigarettes", 1, 1, 1}, {"zomboid:magazine", 2, 1, 1}, {"zomboid:matches", 2, 1, 2},
            {"zomboid:rag", 1, 1, 2}, {"zomboid:empty_bottle", 1, 1, 2}, {"zomboid:cooking_pot", 1, 1, 1},
            {"zomboid:frying_pan", 1, 1, 1}, {"zomboid:seeds_carrot", 1, 1, 2}, {"zomboid:seeds_potato", 1, 1, 2},
        },
        fridge = {
            rolls = {2, 5},
            {"zomboid:raw_meat", 4, 1, 3}, {"zomboid:soda", 4, 1, 3}, {"zomboid:water_bottle", 3, 1, 3},
            {"zomboid:bread", 2, 1, 2}, {"zomboid:apple", 3, 1, 4}, {"zomboid:carrot", 2, 1, 3},
        },
        crate = {
            rolls = {2, 5},
            {"zomboid:potato", 4, 2, 5}, {"zomboid:carrot", 4, 2, 5}, {"zomboid:apple", 4, 2, 5},
            {"zomboid:canned_beans", 4, 2, 6}, {"zomboid:water_bottle", 3, 2, 4}, {"zomboid:chips", 2, 2, 4},
            {"zomboid:soda", 2, 2, 4},
        },
        kitchen_cabinet = {
            {"zomboid:cigarettes", 4, 1, 2}, {"zomboid:matches", 3, 1, 2}, {"zomboid:chocolate", 3, 1, 2},
            {"zomboid:magazine", 2, 1, 1}, {"zomboid:map", 2, 1, 1}, {"zomboid:radio", 1, 1, 1},
        },
    },
    zombies = {count = {6, 10}, yard = {2, 4}},
}
