"zomboid:damage" = {}
"zomboid:knockback" = {}
"zomboid:cooldown" = {}
"zomboid:range" = {}
"zomboid:stamina" = {}
"zomboid:chop" = {}
"zomboid:pry" = {}
"zomboid:hunger" = {}
"zomboid:thirst" = {}
"zomboid:spoil-days" = {}
"zomboid:sickness" = {}
"zomboid:loot" = {}
"zomboid:bash-hp" = {}
"zomboid:skill-book" = {}
"zomboid:book-volume" = {}
"zomboid:gun" = {}
"zomboid:noise-radius" = {}
"zomboid:noise-delay" = {}
"zomboid:noise-time" = {}
"zomboid:weight" = {}
"zomboid:mood" = {}
"zomboid:slot" = {}
"zomboid:warmth" = {}
"zomboid:protection" = {}
"zomboid:waterproof" = {}
"zomboid:slots" = {}
"zomboid:weight-reduction" = {}
"zomboid:crop" = {}
"zomboid:stale" = {}
"zomboid:fresh" = {}
