"zomboid:damage" = {}
"zomboid:knockback" = {}
"zomboid:cooldown" = {}
"zomboid:range" = {}
"zomboid:stamina" = {}
"zomboid:chop" = {}
"zomboid:pry" = {}
"zomboid:hunger" = {}
"zomboid:thirst" = {}
"zomboid:spoil-days" = {}
"zomboid:sickness" = {}
"zomboid:loot" = {}
"zomboid:bash-hp" = {}
"zomboid:skill-book" = {}
"zomboid:book-volume" = {}
